Fix NoClassDefFoundError crashes
Fixes crashes caused by calling a method in a class that has references
to APIs added in API level 23 within Chrome. Now using a custom
callMethod function to prevent these crashes and access fields directly
rather than calling getters.