Fix issues caused by NoClassDefFoundError on Lollipop and below
If XposedHelpers.callMethod throws a NoClassDefFoundError caused by
attempting to resolve classes added in MM, search the object's class and
superclasses for the method using XposedHelpers.findMethodExact